pull_request_rules:
  - name: Assign author
    conditions:
      - "-closed"
      - "#assignee=0"
    actions:
      assign: 
        users:
          - "{{author}}"
  - name: Assign Reviewer
    conditions:
      - author!=BobAnkh
      - "-draft"
      - "-closed"
      - "#review-requested=0"
    actions:
      request_reviews:
        users:
          - BobAnkh
  - name: Assign Reviewer
    conditions:
      - author!=duskmoon314
      - "-draft"
      - "-closed"
      - "#review-requested=0"
    actions:
      request_reviews:
        users:
          - duskmoon314
  - name: conflict comment
    conditions:
      - "-closed"
      - "-draft"
      - "-merged"
      - "conflict"
    actions:
      comment:
        message: |
          @{{author}}
          There are some conflicts within your pull request.
          Could you please fix them?
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - label!=invalid
      - "-closed"
      - "-draft"
      - "-conflict"
      - "-merged"
    actions:
      comment:
        message: |
          This pull request has been approved by:
          {% for name in approved_reviews_by %}
          @{{name}}
          {% endfor %}
          Thank you @{{author}} for your contributions!
      merge:
        method: merge
        strict: smart+fasttrack
        strict_method: rebase
